from __future__ import annotations

# TalkSync AI Theme & Palette Colors
BG_PRIMARY = "#EFEFEF"         # Light grey app background
BG_SECONDARY = "#F3F4F6"       # Soft input/control background
BG_CARD = "#FFFFFF"            # Pure white card background
BG_SIDEBAR = "#FAFAFA"         # Sidebar background

BORDER_COLOR = "#E5E7EB"       # Subtle card/divider border
BORDER_COLOR_LIGHT = "#F3F4F6"

TEXT_PRIMARY = "#111827"       # Dark header text
TEXT_SECONDARY = "#6B7280"     # Subtitle grey text
TEXT_LIGHT = "#FFFFFF"         # White text on dark/colored buttons
TEXT_MUTED = "#9CA3AF"         # Muted label text

ACCENT_ORANGE = "#FF5C2B"      # TalkSync AI signature primary orange
ACCENT_ORANGE_HOVER = "#E54D1F"

ACCENT_BLUE = "#3B82F6"
ACCENT_BLUE_HOVER = "#2563EB"

ACCENT_GREEN = "#10B981"
ACCENT_GREEN_HOVER = "#059669"

ACCENT_RED = "#EF4444"
ACCENT_RED_HOVER = "#DC2626"

ACCENT_PURPLE = "#8B5CF6"
ACCENT_PURPLE_HOVER = "#7C3AED"

ACCENT_AMBER = "#F59E0B"

BADGE_VOICE = "#FF5C2B"
BADGE_TEXT = "#06B6D4"
BADGE_COMPUTER = "#8B5CF6"

STATUS_LISTENING = ACCENT_BLUE
STATUS_PROCESSING = ACCENT_AMBER
STATUS_TRANSLATING = ACCENT_PURPLE
STATUS_SPEAKING = ACCENT_GREEN
STATUS_ERROR = ACCENT_RED
STATUS_IDLE = "#E5E7EB"
STATUS_PAUSED = "#6366F1"

CORNER_RADIUS = 16
CORNER_RADIUS_SMALL = 8
CORNER_RADIUS_LARGE = 20

FONT_FAMILY = "Segoe UI"
FONT_FAMILY_MONO = "Cascadia Code"

FONT_SIZE_SMALL = 11
FONT_SIZE_NORMAL = 13
FONT_SIZE_MEDIUM = 15
FONT_SIZE_LARGE = 18
FONT_SIZE_XLARGE = 22
FONT_SIZE_HERO = 28

WAVEFORM_COLOR = ACCENT_ORANGE
SEND_BUTTON_COLOR = ACCENT_ORANGE
SEND_BUTTON_HOVER = ACCENT_ORANGE_HOVER

TRANSPARENT = "transparent"
SCROLLBAR_COLOR = "#D1D5DB"
SCROLLBAR_HOVER = "#9CA3AF"

PURPLE = ACCENT_PURPLE
ACCENT = ACCENT_ORANGE
TEXT_DARK = TEXT_PRIMARY
WARNING_AMBER = ACCENT_AMBER
SUCCESS_GREEN = ACCENT_GREEN
ERROR_RED = ACCENT_RED

CARD_HOVER_BORDER = ACCENT_ORANGE
